#cloud-config

write_files:
- path: /etc/systemd/system/ethereum.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Dockerized Ethereum Go Client

    [Service]
    ExecStart=/usr/bin/docker \
      run \
      --rm \
      --name=geth \
      --publish=8545:8545 \
      --publish=8546:8546 \
      gcr.io/kosu-io/kosu-geth:0.1.0-zaiden
    ExecStop=/usr/bin/docker stop geth

runcmd:
- systemctl daemon-reload
- systemctl start ethereum.service
